export const curatedWords = [
  { id: "equilibre", word: "équilibre", weight: 3, top: 11, left: 13, size: 1.4, rotate: -6 },
  { id: "jolie", word: "jolie", weight: 5, top: 10, left: 34, size: 2.8, rotate: -2 },
  { id: "chaleureuse", word: "chaleureuse", weight: 5, top: 12, left: 59, size: 2.9, rotate: 3 },
  { id: "sourire", word: "sourire", weight: 4, top: 10, left: 84, size: 2.3, rotate: -2 },
  { id: "taquinerie", word: "taquinerie", weight: 5, top: 24, left: 17, size: 2.8, rotate: -4 },
  { id: "lumineuse", word: "lumineuse", weight: 3, top: 22, left: 42, size: 1.8, rotate: -3 },
  { id: "drole", word: "drôle", weight: 3, top: 22, left: 82, size: 1.8, rotate: -4 },
  { id: "ma-vie", word: "ma vie", weight: 5, top: 34, left: 24, size: 2.6, rotate: 4 },
  { id: "sincere", word: "sincère", weight: 4, top: 30, left: 57, size: 2.6, rotate: 5 },
  { id: "sauver", word: "sauver", weight: 2, top: 28, left: 68, size: 1.4, rotate: -4 },
  { id: "marquante", word: "marquante", weight: 5, top: 48, left: 10, size: 2.8, rotate: -4 },
  { id: "surprise", word: "surprise", weight: 2, top: 46, left: 26, size: 1.5, rotate: 2 },
  { id: "bijou", word: "bijou", weight: 5, top: 44, left: 39, size: 3, rotate: 4 },
  { id: "futur", word: "futur", weight: 3, top: 43, left: 51, size: 1.9, rotate: -2 },
  { id: "femme", word: "femme", weight: 3, top: 43, left: 69, size: 1.9, rotate: -1 },
  { id: "attachante", word: "attachante", weight: 5, top: 40, left: 86, size: 3, rotate: -4 },
  { id: "joie", word: "joie", weight: 5, top: 58, left: 18, size: 2.8, rotate: -2 },
  { id: "mon-amour", word: "mon amour", weight: 5, top: 61, left: 37, size: 2.6, rotate: 4 },
  { id: "toufikette", word: "toufikette", weight: 5, top: 58, left: 63, size: 2.8, rotate: 4 },
  { id: "mon-repere", word: "mon repère", weight: 2, top: 57, left: 80, size: 1.5, rotate: -2 },
  { id: "douce", word: "douce", weight: 5, top: 57, left: 92, size: 2.8, rotate: -2 },
  { id: "serenite", word: "sérénité", weight: 3, top: 71, left: 9, size: 1.6, rotate: -2 },
  { id: "delire", word: "délire", weight: 3, top: 75, left: 31, size: 1.8, rotate: 3 },
  { id: "etincelle", word: "étincelle", weight: 3, top: 74, left: 54, size: 1.7, rotate: -2 },
  { id: "rire", word: "rire", weight: 4, top: 74, left: 76, size: 2.3, rotate: 1 },
  { id: "speciale", word: "spéciale", weight: 3, top: 79, left: 88, size: 1.7, rotate: -3 },
  { id: "legere", word: "légère", weight: 5, top: 88, left: 16, size: 2.9, rotate: 2 },
  { id: "soleil", word: "soleil", weight: 5, top: 95, left: 28, size: 2.9, rotate: -4 },
  { id: "mon-sourire", word: "mon sourire", weight: 2, top: 89, left: 45, size: 1.6, rotate: -3 },
  { id: "simple", word: "simple", weight: 5, top: 87, left: 60, size: 2.9, rotate: -2 },
  { id: "rayonnante", word: "rayonnante", weight: 5, top: 95, left: 84, size: 2.9, rotate: -4 },
  { id: "forte", word: "forte", weight: 3, top: 98, left: 12, size: 1.8, rotate: -6 },
  { id: "rare", word: "rare", weight: 2, top: 98, left: 67, size: 1.5, rotate: -6 }
] as const;
